# Generated by Django 6.1 on 2026-09-09 08:03

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_id_document',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.PrivateIDStorage(), upload_to='guardian_id_documents/'),
        ),
    ]
