# Generated by Django 6.1 on 2026-09-22 18:20

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.PublicMediaStorage(), upload_to='profile_pictures/'),
        ),
    ]
