# Generated by Django 6.1 on 2026-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.CharField(blank=True, help_text='e.g. "3km swim - 180km bike - 42km run"', max_length=200),
        ),
    ]
