# Generated by Django 6.1 on 2026-09-07 09:25

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.PublicMediaStorage(), upload_to='events/'),
        ),
    ]
