# Generated by Django 6.1 on 2026-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_discipline_to_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
