# Generated by Django 6.1 on 2026-09-07 09:25

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.PrivateIDStorage(), upload_to='payment_proofs/'),
        ),
    ]
