# Generated by Django 6.1 on 2026-09-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_payment_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymongo_checkout_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
