# Generated by Django 6.1 on 2026-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_payment_paymongo_checkout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('card', 'Card'), ('paymaya', 'Maya'), ('palawanpay', 'PalawanPay')], max_length=20),
        ),
    ]
