# Generated by Django 6.1 on 2026-09-14 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_discipline_to_event_type'),
        ('registrations', '0004_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('bib_number', ''), _negated=True), fields=('event_category', 'bib_number'), name='unique_bib_number_per_category'),
        ),
    ]
