# Generated by Django 6.1 on 2026-09-07 09:25

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypostimage',
            name='image',
            field=models.ImageField(storage=config.storage_backends.PublicMediaStorage(), upload_to='community_posts/'),
        ),
    ]
